version: "3.9"
services:
  server:
    build: Backend
    ports:
      - "8000:3000"
    env_file:
      - Backend/.env
  pwa:
    build: Frontend
    ports:
      - "8088:80"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  redis:
    image: redis