name: Docker Image CI Google

on:
  push:
    paths:
      - "Frontend/**"
      - "Backend/**"
      - ".github/workflows/docker-image-gcr.yaml"
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GCR
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: gcloud auth configure-docker eu.gcr.io --quiet
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: Frontend        
        platforms: linux/amd64      
        push: true
        labels: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-computing-frontend
        tags: latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GCR
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: gcloud auth configure-docker eu.gcr.io --quiet
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: Backend        
        platforms: linux/amd64      
        push: true
        labels: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/cloud-computing-backend
        tags: latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
